[package]
name = "rustwar"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format= "0.4.0"
pbr = "1.0.4"
rand = "0.8.4"
strum = "0.22"
strum_macros = "0.22"
